<%@ page language="java" contentType="text/html; charset=ISO-8859-1"
    pageEncoding="ISO-8859-1"%>
    <%@ taglib prefix="s" uri="/struts-tags"%>
    <%@ taglib prefix="sx" uri="/struts-dojo-tags"%>
<div class="threecol">
  <div id="colCont"> 
    <!-- Dashboard Pane starts and col1 is the class for dashboards -->
    <div id="col1">&nbsp;Dashboards
      <div id="dashboard"> Dummy Graph only  Dummy Graph only  Dummy Graph only  Dummy Graph only  Dummy Graph only  Dummy Graph only  Dummy Graph only  Dummy Graph only  Dummy Graph only  Dummy Graph only  Dummy Graph only  Dummy Graph only  Dummy Graph only  Dummy Graph only  Dummy Graph only  Dummy Graph only  Dummy Graph only  Dummy Graph only  Dummy Graph only  Dummy Graph only  Dummy Graph only ><img src="images/chart.jpg" width="355" height="191" /> Dummy Graph only  Dummy Graph only  Dummy Graph only  Dummy Graph only  Dummy Graph only  Dummy Graph only  Dummy Graph only  Dummy Graph only  Dummy Graph only  Dummy Graph only  Dummy Graph only  Dummy Graph only  Dummy Graph only  Dummy Graph only  Dummy Graph only  Dummy Graph only  Dummy Graph only  Dummy Graph only  Dummy Graph only  Dummy Graph only  Dummy Graph only  Dummy Graph only  Dummy Graph only  Dummy Graph only  Dummy Graph only  Dummy Graph only  Dummy Graph only  Dummy Graph only  Dummy Graph only  Dummy Graph only  Dummy Graph only  Dummy Graph only  Dummy Graph only  Dummy Graph only  Dummy Graph only  Dummy Graph only  Dummy Graph only  Dummy Graph only  Dummy Graph only  Dummy Graph only  Dummy Graph only  Dummy Graph only  Dummy Graph only  Dummy Graph only  Dummy Graph only  Dummy Graph only  Dummy Graph only  Dummy Graph only  Dummy Graph only  Dummy Graph only  Dummy Graph only  Dummy Graph only  Dummy Graph only  Dummy Graph only  Dummy Graph only  Dummy Graph only  Dummy Graph only  Dummy Graph only  Dummy Graph only  Dummy Graph only  Dummy Graph only  Dummy Graph only  Dummy Graph only  Dummy Graph only  Dummy Graph only  Dummy Graph only  Dummy Graph only  Dummy Graph only  Dummy Graph only  Dummy Graph only  Dummy Graph only  Dummy Graph only  Dummy Graph only  Dummy Graph only  Dummy Graph only  Dummy Graph only  Dummy Graph only  Dummy Graph only  Dummy Graph only  Dummy Graph only  Dummy Graph only  Dummy Graph only  Dummy Graph only  Dummy Graph only  Dummy Graph only  Dummy Graph only  Dummy Graph only  Dummy Graph only  Dummy Graph only  Dummy Graph only  Dummy Graph only  Dummy Graph only  Dummy Graph only  Dummy Graph only  Dummy Graph only  Dummy Graph only  Dummy Graph only  Dummy Graph only  Dummy Graph only  Dummy Graph only  Dummy Graph only  Dummy Graph only  Dummy Graph only  Dummy Graph only  Dummy Graph only  Dummy Graph only  Dummy Graph only  Dummy Graph only  Dummy Graph only  Dummy Graph only  Dummy Graph only  Dummy Graph only  Dummy Graph only  Dummy Graph only  Dummy Graph only  Dummy Graph only  Dummy Graph only  Dummy Graph only  Dummy Graph only  Dummy Graph only  Dummy Graph only  Dummy Graph only  Dummy Graph only  Dummy Graph only </div>
    </div>
    <!-- Dashboard Pane ends --> 
    <!-- Queue Pane starts and col2 is the class for queues-->
    <div id="col2">&nbsp;Queues
      <div id="queues"><img src="images/queuesTab.jpg" width="237" height="308" /><img src="images/queuesTab.jpg" width="237" height="308" /></div>
    </div>
    <!-- Queue Pane ends --> 
    <!-- Content Pane starts and col3 is the class for contnet-->
    <div id="col3">&nbsp;Content
      <div id="content">
        <p>Dummy content only.Dummy content only.Dummy content only.Dummy content only.Dummy content only.Dummy content only.Dummy content only.Dummy content only.Dummy content only.Dummy content only.Dummy content only.Dummy content only.Dummy content only.Dummy content only.Dummy content only.Dummy content only.Dummy content only.Dummy content only.Dummy content only.Dummy content only.Dummy content only.Dummy content only.Dummy content only.Dummy content only.Dummy content only.Dummy content only.Dummy content only.Dummy content only.Dummy content only.Dummy content only.Dummy content only.Dummy content only.Dummy content only.Dummy content only.Dummy content only.Dummy content only.Dummy content only.Dummy content only.Dummy content only.Dummy content only.Dummy content only.Dummy content only.Dummy content only.Dummy content only.Dummy content only.Dummy content only.Dummy content only.Dummy content only.Dummy content only.Dummy content only.Dummy content only.Dummy content only.Dummy content only.Dummy content only.Dummy content only.Dummy content only.Dummy content only.Dummy content only.Dummy content only.Dummy content only.Dummy content only.Dummy content only.Dummy content only.Dummy content only.Dummy content only.Dummy content only.Dummy content only.</p>
        <p>Dummy content only.Dummy content only.Dummy content only.Dummy content only.Dummy content only.Dummy content only.Dummy content only.Dummy content only.Dummy content only.Dummy content only.Dummy content only.Dummy content only.Dummy content only.Dummy content only.Dummy content only.Dummy content only.Dummy content only.Dummy content only.Dummy content only.Dummy content only.Dummy content only.Dummy content only.Dummy content only.Dummy content only.Dummy content only.Dummy content only.Dummy content only.Dummy content only.Dummy content only.Dummy content only.Dummy content only.Dummy content only.Dummy content only.Dummy content only.Dummy content only.Dummy content only.Dummy content only.Dummy content only.Dummy content only.Dummy content only.Dummy content only.Dummy content only.Dummy content only.Dummy content only.Dummy content only.Dummy content only.Dummy content only.Dummy content only.Dummy content only.Dummy content only.Dummy content only.Dummy content only.Dummy content only.Dummy content only.Dummy content only.Dummy content only.Dummy content only.Dummy content only.Dummy content only.Dummy content only.Dummy content only.Dummy content only.Dummy content only.Dummy content only.Dummy content only.Dummy content only.Dummy content only.</p>
        <p>Dummy content only.Dummy content only.Dummy content only.Dummy content only.Dummy content only.Dummy content only.Dummy content only.Dummy content only.Dummy content only.Dummy content only.Dummy content only.Dummy content only.Dummy content only.Dummy content only.Dummy content only.Dummy content only.Dummy content only.Dummy content only.Dummy content only.Dummy content only.Dummy content only.Dummy content only.Dummy content only.Dummy content only.Dummy content only.Dummy content only.Dummy content only.Dummy content only.Dummy content only.Dummy content only.Dummy content only.Dummy content only.Dummy content only.Dummy content only.Dummy content only.Dummy content only.Dummy content only.Dummy content only.Dummy content only.Dummy content only.Dummy content only.Dummy content only.Dummy content only.Dummy content only.Dummy content only.Dummy content only.Dummy content only.Dummy content only.Dummy content only.Dummy content only.Dummy content only.Dummy content only.Dummy content only.Dummy content only.Dummy content only.Dummy content only.Dummy content only.Dummy content only.Dummy content only.Dummy content only.Dummy content only.Dummy content only.Dummy content only.Dummy content only.Dummy content only.Dummy content only.Dummy content only.</p>
        <p>Dummy content only.Dummy content only.Dummy content only.Dummy content only.Dummy content only.Dummy content only.Dummy content only.Dummy content only.Dummy content only.Dummy content only.Dummy content only.Dummy content only.Dummy content only.Dummy content only.Dummy content only.Dummy content only.Dummy content only.Dummy content only.Dummy content only.Dummy content only.Dummy content only.Dummy content only.Dummy content only.Dummy content only.Dummy content only.Dummy content only.Dummy content only.Dummy content only.Dummy content only.Dummy content only.Dummy content only.Dummy content only.Dummy content only.Dummy content only.Dummy content only.Dummy content only.Dummy content only.Dummy content only.Dummy content only.Dummy content only.Dummy content only.Dummy content only.Dummy content only.Dummy content only.Dummy content only.Dummy content only.Dummy content only.Dummy content only.Dummy content only.Dummy content only.Dummy content only.Dummy content only.Dummy content only.Dummy content only.Dummy content only.Dummy content only.Dummy content only.Dummy content only.Dummy content only.Dummy content only.Dummy content only.Dummy content only.Dummy content only.Dummy content only.Dummy content only.Dummy content only.Dummy content only.</p>
        <p>Dummy content only.Dummy content only.Dummy content only.Dummy content only.Dummy content only.Dummy content only.Dummy content only.Dummy content only.Dummy content only.Dummy content only.Dummy content only.Dummy content only.Dummy content only.Dummy content only.Dummy content only.Dummy content only.Dummy content only.Dummy content only.Dummy content only.Dummy content only.Dummy content only.Dummy content only.Dummy content only.Dummy content only.Dummy content only.Dummy content only.Dummy content only.Dummy content only.Dummy content only.Dummy content only.Dummy content only.Dummy content only.Dummy content only.Dummy content only.Dummy content only.Dummy content only.Dummy content only.Dummy content only.Dummy content only.Dummy content only.Dummy content only.Dummy content only.Dummy content only.Dummy content only.Dummy content only.Dummy content only.Dummy content only.Dummy content only.Dummy content only.Dummy content only.Dummy content only.Dummy content only.Dummy content only.Dummy content only.Dummy content only.Dummy content only.Dummy content only.Dummy content only.Dummy content only.Dummy content only.Dummy content only.Dummy content only.Dummy content only.Dummy content only.Dummy content only.Dummy content only.Dummy content only.</p>
      </div>
    </div>
    <!-- Content Pane ends --> 
  </div>
</div>

